/** 
 * @type {{ [key: string]: string }}
 */
const customMapping = {
  js: "javascript",
  jsx: "jsx",
  ts: "typescript",
  tsx: "typescript",
  py: "python",
  java: "java",
  c: "cpp",
  cpp: "cpp",
  h: "cpp",
  cs: "csharp",
  php: "php",
  rb: "ruby",
  go: "go",
  rs: "rust",
  swift: "swift",
  kt: "kotlin",
  kts: "kotlin",
  sh: "shell",
  bash: "shell",
  html: "html",
  css: "css",
  scss: "scss",
  less: "less",
  json: "json",
  xml: "xml",
  yaml: "yaml",
  yml: "yaml",
  md: "markdown",
  sql: "sql",
  dart: "dart",
  scala: "scala",
  lua: "lua",
  perl: "perl",
  r: "r",
  pl: "perl",
  vue: "vue",
  svelte: "svelte",
  dockerfile: "dockerfile",
  makefile: "makefile",
  ini: "ini",
  toml: "toml",
  conf: "ini",
  tex: "latex",
  asm: "assembly",
  vb: "vb",
  groovy: "groovy",
  objectivec: "objectivec",
  objc: "objectivec",
  coffee: "coffeescript",
  clj: "clojure",
  fs: "fsharp",
  ml: "ocaml",
  dart: "dart",
  // Add more as needed
}

export default customMapping

