import {
  abcdef,abyss,androidstudio,andromeda,atomone,aura,basicDark,basicLight,bbedit,bespin,copilot,darcula,dracula,duotoneDark,duotoneLight,eclipse,
  githubDark,githubLight,gruvboxDark,gruvboxLight,kimbie,material,materialDark,materialLight,monokaiDimmed,noctisLilac,nord,okaidia,quietlight,red,solarizedDark,
  solarizedLight,sublime,tokyoNight,tokyoNightDay,tokyoNightStorm,tomorrowNightBlue,vscodeDark,whiteDark,whiteLight,xcodeDark,xcodeLight,
} from "@uiw/codemirror-themes-all"

export const editorThemes = {
  Abcdef: abcdef,
  Abyss: abyss,
  "Android Studio": androidstudio,
  Andromeda: andromeda,
  "Atom One": atomone,
  Aura: aura,
  "Basic Dark": basicDark,
  "Basic Light": basicLight,
  BBEdit: bbedit,
  Bespin: bespin,
  Copilot: copilot,
  Darcula: darcula,
  Dracula: dracula,
  "Duotone Dark": duotoneDark,
  "Duotone Light": duotoneLight,
  Eclipse: eclipse,
  "GitHub Dark": githubDark,
  "GitHub Light": githubLight,
  "Gruvbox Dark": gruvboxDark,
  "Gruvbox Light": gruvboxLight,
  Kimbie: kimbie,
  Material: material,
  "Material Dark": materialDark,
  "Material Light": materialLight,
  Monokai: monokaiDimmed,
  "Monokai Dimmed": monokaiDimmed,
  "Noctis Lilac": noctisLilac,
  Nord: nord,
  Okaidia: okaidia,
  "Quiet Light": quietlight,
  Red: red,
  "Solarized Dark": solarizedDark,
  "Solarized Light": solarizedLight,
  Sublime: sublime,
  "Tokyo Night": tokyoNight,
  "Tokyo Night Day": tokyoNightDay,
  "Tokyo Night Storm": tokyoNightStorm,
  "Tomorrow Night Blue": tomorrowNightBlue,
  "VS Code Dark": vscodeDark,
  "White Dark": whiteDark,
  "White Light": whiteLight,
  "Xcode Dark": xcodeDark,
  "Xcode Light": xcodeLight,
}

